Reaktor_Assignment/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('package_finder.urls')),
    path('admin/', admin.site.urls),
]

package_finder/urls.py
from django.urls import path

from . import views

app_name = "package_finder"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:package_id>/', views.detail, name='detail'),
]

package_finder/models.py
from django.db import models


class Package(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    depend_package = models.ManyToManyField('self', symmetrical=False,
                                            through='Dependency')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Dependency(models.Model):
    pack = models.ForeignKey(Package, on_delete=models.CASCADE,
                             related_name='depends_on')
    dependant = models.ForeignKey(Package, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('pack', 'dependant')


class AlterDependency(models.Model):
    name = models.CharField(max_length=100, null=False)
    package = models.ForeignKey(Package, on_delete=models.CASCADE,
                                related_name='alter_depends_on')

    class Meta:
        unique_together = ('name', 'package')

package_finder/views.py
from django.shortcuts import render, get_object_or_404
from package_finder.models import Package


def index(request):

    context = {
        "packages_list": Package.objects.all()
    }

    return render(request, "index.html", context)


def detail(request, package_id):

    package_obj = get_object_or_404(Package, pk=package_id)
    depends = package_obj.depends_on.all()
    alter_depends = package_obj.alter_depends_on.all()

    context = {'package': package_obj,
               'depends': depends,
               'alter_depends': alter_depends}

    return render(request, "detail.html", context)

package_finder/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ package.name }}</title>
</head>
<body>

<h3> PACKAGE NAME: </h3>
<p>{{ package.name }}</p>

<h3> DESCRIPTION: </h3>
    <pre>{{ package.description }}</pre>

<h3> DEPENDENCIES: </h3>
<ul>
{% for dep_pack in depends %}
    <li>
        <a href="{% url 'package_finder:detail' dep_pack.dependant.id %}">
        {{ dep_pack.dependant.name }}</a>
    </li>
{% endfor %}

{% for alter_dep_pack in alter_depends %}
    <li>{{ alter_dep_pack.name }}</li>
{% endfor %}
</ul>

</body>
</html>

package_finder/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Installed Packages</title>
</head>
<body>
<ul>

  {% for package in packages_list %}
  <li>
      <a href="{% url 'package_finder:detail' package.id %}">{{ package.name }}
      </a>
  </li>
  {% endfor %}

</ul>
</body>
</html>